### ISSUE TITLE
AttributeError: 'QComboBox' object has no attribute 'setPlaceholderText'

### ISSUE THREAD

**Issue by alkorgun** [CineEncoder/cine-encoder#2]
- OS: openSUSE 15.2, Ubuntu 20.04, Fedora 32
- Cine-encoder: 2.2
- Python: 3.6-8
- Qt: 5.11-14

```python
$ python3 -m cine_encoder.main
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/cine_encoder/main.py", line 946, in <module>
    main()  # run main()
  File "/usr/lib/python3/dist-packages/cine_encoder/main.py", line 941, in main
    window = ExampleApp()
  File "/usr/lib/python3/dist-packages/cine_encoder/main.py", line 34, in __init__
    self.setupUi(self)
  File "/usr/lib/python3/dist-packages/cine_encoder/ui_main.py", line 787, in setupUi
    self.comboBox_9.setPlaceholderText("")
AttributeError: 'QComboBox' object has no attribute 'setPlaceholderText'
```

I couldn't find PyQt5 documentation older than 5.15, so I'm not sure if it even should to work.

**Comment by CineEncoder** [comment]
Ok, thanks!
I'll watch it today.
With 'setPlaceholderText' of course a strange error, in Manjaro Linux works without problems, I'll try to figure out what it is.

**Comment by CineEncoder** [comment]
Hi!
I fixed the error "object has no attribute 'setPlaceholderText'", a .deb package is working.

**Comment by alkorgun** [comment]
В связи с переходом на плюсы более не актуально.
